//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAM.Elfec.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGAM.Elfec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nueva aplicación.
        /// </summary>
        public static string BtnAddApp {
            get {
                return ResourceManager.GetString("BtnAddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar.
        /// </summary>
        public static string BtnAuthorize {
            get {
                return ResourceManager.GetString("BtnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        public static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir aplicación.
        /// </summary>
        public static string BtnUploadApp {
            get {
                return ResourceManager.GetString("BtnUploadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizado.
        /// </summary>
        public static string DeviceStatusAuthorized {
            get {
                return ResourceManager.GetString("DeviceStatusAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de autorización.
        /// </summary>
        public static string DeviceStatusAuthPending {
            get {
                return ResourceManager.GetString("DeviceStatusAuthPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No autorizado.
        /// </summary>
        public static string DeviceStatusUnauthorized {
            get {
                return ResourceManager.GetString("DeviceStatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos APK (*.apk)|*.apk.
        /// </summary>
        public static string FileAPKFilter {
            get {
                return ResourceManager.GetString("FileAPKFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nueva aplicación.
        /// </summary>
        public static string LblAddNewApp {
            get {
                return ResourceManager.GetString("LblAddNewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo APK:.
        /// </summary>
        public static string LblApplicationApkFilename {
            get {
                return ResourceManager.GetString("LblApplicationApkFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre aplicación:.
        /// </summary>
        public static string LblApplicationName {
            get {
                return ResourceManager.GetString("LblApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre paquete:.
        /// </summary>
        public static string LblApplicationPackage {
            get {
                return ResourceManager.GetString("LblApplicationPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        public static string LblApplicationVersion {
            get {
                return ResourceManager.GetString("LblApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar dispositivo.
        /// </summary>
        public static string LblAuthorizeDevice {
            get {
                return ResourceManager.GetString("LblAuthorizeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        public static string LblCameraUnit {
            get {
                return ResourceManager.GetString("LblCameraUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión banda base:.
        /// </summary>
        public static string LblDeviceBasebandVersion {
            get {
                return ResourceManager.GetString("LblDeviceBasebandVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección MAC bluetooth:.
        /// </summary>
        public static string LblDeviceBluetoothMac {
            get {
                return ResourceManager.GetString("LblDeviceBluetoothMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca:.
        /// </summary>
        public static string LblDeviceBrand {
            get {
                return ResourceManager.GetString("LblDeviceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cámara:.
        /// </summary>
        public static string LblDeviceCamera {
            get {
                return ResourceManager.GetString("LblDeviceCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios:.
        /// </summary>
        public static string LblDeviceComments {
            get {
                return ResourceManager.GetString("LblDeviceComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta gmail:.
        /// </summary>
        public static string LblDeviceGmailAccount {
            get {
                return ResourceManager.GetString("LblDeviceGmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Cisco ASA:.
        /// </summary>
        public static string LblDeviceIdCiscoASA {
            get {
                return ResourceManager.GetString("LblDeviceIdCiscoASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI:.
        /// </summary>
        public static string LblDeviceIMEI {
            get {
                return ResourceManager.GetString("LblDeviceIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo:.
        /// </summary>
        public static string LblDeviceModel {
            get {
                return ResourceManager.GetString("LblDeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string LblDeviceName {
            get {
                return ResourceManager.GetString("LblDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        public static string LblDeviceOSVersion {
            get {
                return ResourceManager.GetString("LblDeviceOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° teléfono:.
        /// </summary>
        public static string LblDevicePhoneNumber {
            get {
                return ResourceManager.GetString("LblDevicePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema operativo:.
        /// </summary>
        public static string LblDevicePlatform {
            get {
                return ResourceManager.GetString("LblDevicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolución pantalla:.
        /// </summary>
        public static string LblDeviceScreenRes {
            get {
                return ResourceManager.GetString("LblDeviceScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño pantalla:.
        /// </summary>
        public static string LblDeviceScreenSize {
            get {
                return ResourceManager.GetString("LblDeviceScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Memoria:.
        /// </summary>
        public static string LblDeviceSDMemoryCard {
            get {
                return ResourceManager.GetString("LblDeviceSDMemoryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° de serie:.
        /// </summary>
        public static string LblDeviceSerial {
            get {
                return ResourceManager.GetString("LblDeviceSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        public static string LblDeviceStatus {
            get {
                return ResourceManager.GetString("LblDeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección MAC wifi:.
        /// </summary>
        public static string LblDeviceWifiMac {
            get {
                return ResourceManager.GetString("LblDeviceWifiMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LblLogin {
            get {
                return ResourceManager.GetString("LblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string LblMemoryUnit {
            get {
                return ResourceManager.GetString("LblMemoryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulg..
        /// </summary>
        public static string LblSizeUnit {
            get {
                return ResourceManager.GetString("LblSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string LblStatusbarDefault {
            get {
                return ResourceManager.GetString("LblStatusbarDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar dispositivo.
        /// </summary>
        public static string MenuItemAuthorizeDevice {
            get {
                return ResourceManager.GetString("MenuItemAuthorizeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizando dispositivo….
        /// </summary>
        public static string MsgAuthorizingDevice {
            get {
                return ResourceManager.GetString("MsgAuthorizingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo {0} fue autorizado correctamente.
        /// </summary>
        public static string MsgDeviceSuccessfullyAuthorized {
            get {
                return ResourceManager.GetString("MsgDeviceSuccessfullyAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos tienen errores, corrigalos para poder continuar..
        /// </summary>
        public static string MsgErrorsInFields {
            get {
                return ResourceManager.GetString("MsgErrorsInFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información del APK, este proceso puede tardar dependiendo del tamaño del archivo, espere por favor….
        /// </summary>
        public static string MsgLoadingApk {
            get {
                return ResourceManager.GetString("MsgLoadingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información del APK….
        /// </summary>
        public static string MsgLoadingApkShort {
            get {
                return ResourceManager.GetString("MsgLoadingApkShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información de aplicaciones….
        /// </summary>
        public static string MsgLoadingApps {
            get {
                return ResourceManager.GetString("MsgLoadingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información de dispositivos….
        /// </summary>
        public static string MsgLoadingDevices {
            get {
                return ResourceManager.GetString("MsgLoadingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando información de usuario….
        /// </summary>
        public static string MsgLoginUser {
            get {
                return ResourceManager.GetString("MsgLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exito!.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono de la aplicación.
        /// </summary>
        public static string TooltipApplicationIcon {
            get {
                return ResourceManager.GetString("TooltipApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir atrás.
        /// </summary>
        public static string TooltipBack {
            get {
                return ResourceManager.GetString("TooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver aplicaciones.
        /// </summary>
        public static string TooltipShowApps {
            get {
                return ResourceManager.GetString("TooltipShowApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver dispositivos.
        /// </summary>
        public static string TooltipShowDevices {
            get {
                return ResourceManager.GetString("TooltipShowDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver usuarios.
        /// </summary>
        public static string TooltipShowUsers {
            get {
                return ResourceManager.GetString("TooltipShowUsers", resourceCulture);
            }
        }
    }
}
