//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAM.Elfec.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGAM.Elfec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitado.
        /// </summary>
        public static string ApiStatusDisabled {
            get {
                return ResourceManager.GetString("ApiStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        public static string ApiStatusEnabled {
            get {
                return ResourceManager.GetString("ApiStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar reglas de directivas de usuario.
        /// </summary>
        public static string BtnAddPolicyRule {
            get {
                return ResourceManager.GetString("BtnAddPolicyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación.
        /// </summary>
        public static string BtnApplication {
            get {
                return ResourceManager.GetString("BtnApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar.
        /// </summary>
        public static string BtnAuthorize {
            get {
                return ResourceManager.GetString("BtnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        public static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas de directivas de usuario.
        /// </summary>
        public static string BtnPolicyRule {
            get {
                return ResourceManager.GetString("BtnPolicyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir aplicación.
        /// </summary>
        public static string BtnUploadApp {
            get {
                return ResourceManager.GetString("BtnUploadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string BtnUser {
            get {
                return ResourceManager.GetString("BtnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de usuarios.
        /// </summary>
        public static string BtnUserGroup {
            get {
                return ResourceManager.GetString("BtnUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizado.
        /// </summary>
        public static string DeviceStatusAuthorized {
            get {
                return ResourceManager.GetString("DeviceStatusAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de autorización.
        /// </summary>
        public static string DeviceStatusAuthPending {
            get {
                return ResourceManager.GetString("DeviceStatusAuthPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No autorizado.
        /// </summary>
        public static string DeviceStatusUnauthorized {
            get {
                return ResourceManager.GetString("DeviceStatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos APK (*.apk)|*.apk.
        /// </summary>
        public static string FileAPKFilter {
            get {
                return ResourceManager.GetString("FileAPKFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string HintSearch {
            get {
                return ResourceManager.GetString("HintSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nueva aplicación.
        /// </summary>
        public static string LblAddNewApp {
            get {
                return ResourceManager.GetString("LblAddNewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar nuevo usuario.
        /// </summary>
        public static string LblAddNewUser {
            get {
                return ResourceManager.GetString("LblAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar reglas de directivas de usuario.
        /// </summary>
        public static string LblAddPolicyRule {
            get {
                return ResourceManager.GetString("LblAddPolicyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nuevo grupo de usuarios.
        /// </summary>
        public static string LblAddUserGroup {
            get {
                return ResourceManager.GetString("LblAddUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar miembros al grupo.
        /// </summary>
        public static string LblAddUserGroupMembers {
            get {
                return ResourceManager.GetString("LblAddUserGroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo APK:.
        /// </summary>
        public static string LblApplicationApkFilename {
            get {
                return ResourceManager.GetString("LblApplicationApkFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última versión.
        /// </summary>
        public static string LblApplicationLatestVersion {
            get {
                return ResourceManager.GetString("LblApplicationLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre aplicación:.
        /// </summary>
        public static string LblApplicationName {
            get {
                return ResourceManager.GetString("LblApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre paquete.
        /// </summary>
        public static string LblApplicationPackage {
            get {
                return ResourceManager.GetString("LblApplicationPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LblApplicationStatus {
            get {
                return ResourceManager.GetString("LblApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión.
        /// </summary>
        public static string LblApplicationVersion {
            get {
                return ResourceManager.GetString("LblApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de versión.
        /// </summary>
        public static string LblApplicationVersionCode {
            get {
                return ResourceManager.GetString("LblApplicationVersionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiones.
        /// </summary>
        public static string LblApplicationVersions {
            get {
                return ResourceManager.GetString("LblApplicationVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar dispositivo.
        /// </summary>
        public static string LblAuthorizeDevice {
            get {
                return ResourceManager.GetString("LblAuthorizeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        public static string LblCameraUnit {
            get {
                return ResourceManager.GetString("LblCameraUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string LblDelete {
            get {
                return ResourceManager.GetString("LblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión banda base:.
        /// </summary>
        public static string LblDeviceBasebandVersion {
            get {
                return ResourceManager.GetString("LblDeviceBasebandVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección MAC bluetooth:.
        /// </summary>
        public static string LblDeviceBluetoothMac {
            get {
                return ResourceManager.GetString("LblDeviceBluetoothMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca:.
        /// </summary>
        public static string LblDeviceBrand {
            get {
                return ResourceManager.GetString("LblDeviceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cámara:.
        /// </summary>
        public static string LblDeviceCamera {
            get {
                return ResourceManager.GetString("LblDeviceCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios:.
        /// </summary>
        public static string LblDeviceComments {
            get {
                return ResourceManager.GetString("LblDeviceComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta gmail:.
        /// </summary>
        public static string LblDeviceGmailAccount {
            get {
                return ResourceManager.GetString("LblDeviceGmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Cisco ASA:.
        /// </summary>
        public static string LblDeviceIdCiscoASA {
            get {
                return ResourceManager.GetString("LblDeviceIdCiscoASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI:.
        /// </summary>
        public static string LblDeviceIMEI {
            get {
                return ResourceManager.GetString("LblDeviceIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo:.
        /// </summary>
        public static string LblDeviceModel {
            get {
                return ResourceManager.GetString("LblDeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string LblDeviceName {
            get {
                return ResourceManager.GetString("LblDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        public static string LblDeviceOSVersion {
            get {
                return ResourceManager.GetString("LblDeviceOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° teléfono:.
        /// </summary>
        public static string LblDevicePhoneNumber {
            get {
                return ResourceManager.GetString("LblDevicePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema operativo:.
        /// </summary>
        public static string LblDevicePlatform {
            get {
                return ResourceManager.GetString("LblDevicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolución pantalla:.
        /// </summary>
        public static string LblDeviceScreenRes {
            get {
                return ResourceManager.GetString("LblDeviceScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño pantalla:.
        /// </summary>
        public static string LblDeviceScreenSize {
            get {
                return ResourceManager.GetString("LblDeviceScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Memoria:.
        /// </summary>
        public static string LblDeviceSDMemoryCard {
            get {
                return ResourceManager.GetString("LblDeviceSDMemoryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° de serie:.
        /// </summary>
        public static string LblDeviceSerial {
            get {
                return ResourceManager.GetString("LblDeviceSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        public static string LblDeviceStatus {
            get {
                return ResourceManager.GetString("LblDeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección MAC wifi:.
        /// </summary>
        public static string LblDeviceWifiMac {
            get {
                return ResourceManager.GetString("LblDeviceWifiMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LblLogin {
            get {
                return ResourceManager.GetString("LblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string LblMemoryUnit {
            get {
                return ResourceManager.GetString("LblMemoryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegar atrás.
        /// </summary>
        public static string LblNavBack {
            get {
                return ResourceManager.GetString("LblNavBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegar adelante.
        /// </summary>
        public static string LblNavForward {
            get {
                return ResourceManager.GetString("LblNavForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo miembro.
        /// </summary>
        public static string LblNewMember {
            get {
                return ResourceManager.GetString("LblNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aun no se agregó ningún miembro al grupo….
        /// </summary>
        public static string LblNoCurrentMembers {
            get {
                return ResourceManager.GetString("LblNoCurrentMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directivas de usuario.
        /// </summary>
        public static string LblPolicies {
            get {
                return ResourceManager.GetString("LblPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string LblPolicyDescription {
            get {
                return ResourceManager.GetString("LblPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han definido reglas para ésta directiva.
        /// </summary>
        public static string LblPolicyEmptyRules {
            get {
                return ResourceManager.GetString("LblPolicyEmptyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas.
        /// </summary>
        public static string LblPolicyRules {
            get {
                return ResourceManager.GetString("LblPolicyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas ({0}).
        /// </summary>
        public static string LblPolicyRulesCount {
            get {
                return ResourceManager.GetString("LblPolicyRulesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LblPolicyStatus {
            get {
                return ResourceManager.GetString("LblPolicyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string LblRuleAction {
            get {
                return ResourceManager.GetString("LblRuleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepciones.
        /// </summary>
        public static string LblRuleException {
            get {
                return ResourceManager.GetString("LblRuleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string LblRuleName {
            get {
                return ResourceManager.GetString("LblRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string LblRuleUsers {
            get {
                return ResourceManager.GetString("LblRuleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición.
        /// </summary>
        public static string LblRuleValue {
            get {
                return ResourceManager.GetString("LblRuleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver aplicaciones.
        /// </summary>
        public static string LblShowApps {
            get {
                return ResourceManager.GetString("LblShowApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver dispositivos.
        /// </summary>
        public static string LblShowDevices {
            get {
                return ResourceManager.GetString("LblShowDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver usuarios.
        /// </summary>
        public static string LblShowUsers {
            get {
                return ResourceManager.GetString("LblShowUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulg..
        /// </summary>
        public static string LblSizeUnit {
            get {
                return ResourceManager.GetString("LblSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string LblStatusbarDefault {
            get {
                return ResourceManager.GetString("LblStatusbarDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        public static string LblUserCompanyArea {
            get {
                return ResourceManager.GetString("LblUserCompanyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblUserEmail {
            get {
                return ResourceManager.GetString("LblUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre completo.
        /// </summary>
        public static string LblUserFullName {
            get {
                return ResourceManager.GetString("LblUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de usuarios.
        /// </summary>
        public static string LblUserGroup {
            get {
                return ResourceManager.GetString("LblUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string LblUserGroupDescription {
            get {
                return ResourceManager.GetString("LblUserGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miembros de grupo.
        /// </summary>
        public static string LblUserGroupMembers {
            get {
                return ResourceManager.GetString("LblUserGroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string LblUserGroupName {
            get {
                return ResourceManager.GetString("LblUserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string LblUserPosition {
            get {
                return ResourceManager.GetString("LblUserPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string LblUsers {
            get {
                return ResourceManager.GetString("LblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LblUserUsername {
            get {
                return ResourceManager.GetString("LblUserUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistas.
        /// </summary>
        public static string LblViews {
            get {
                return ResourceManager.GetString("LblViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar dispositivo.
        /// </summary>
        public static string MenuItemAuthorizeDevice {
            get {
                return ResourceManager.GetString("MenuItemAuthorizeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación {0} fue registrada exitosamente.
        /// </summary>
        public static string MsgApplicationUploadedSuccessfully {
            get {
                return ResourceManager.GetString("MsgApplicationUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizando dispositivo….
        /// </summary>
        public static string MsgAuthorizingDevice {
            get {
                return ResourceManager.GetString("MsgAuthorizingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo {0} fue autorizado correctamente.
        /// </summary>
        public static string MsgDeviceSuccessfullyAuthorized {
            get {
                return ResourceManager.GetString("MsgDeviceSuccessfullyAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista de usuarios está vacía. Pruebe otros filtros de búsqueda..
        /// </summary>
        public static string MsgEmptyUserList {
            get {
                return ResourceManager.GetString("MsgEmptyUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos tienen errores, corrigalos para poder continuar..
        /// </summary>
        public static string MsgErrorsInFields {
            get {
                return ResourceManager.GetString("MsgErrorsInFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información del APK, este proceso puede tardar dependiendo del tamaño del archivo, espere por favor….
        /// </summary>
        public static string MsgLoadingApk {
            get {
                return ResourceManager.GetString("MsgLoadingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información del APK….
        /// </summary>
        public static string MsgLoadingApkShort {
            get {
                return ResourceManager.GetString("MsgLoadingApkShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información de aplicaciones….
        /// </summary>
        public static string MsgLoadingApps {
            get {
                return ResourceManager.GetString("MsgLoadingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información de dispositivos….
        /// </summary>
        public static string MsgLoadingDevices {
            get {
                return ResourceManager.GetString("MsgLoadingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información de usuarios….
        /// </summary>
        public static string MsgLoadingUsers {
            get {
                return ResourceManager.GetString("MsgLoadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando información de usuario….
        /// </summary>
        public static string MsgLoginUser {
            get {
                return ResourceManager.GetString("MsgLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrando usuario para su uso de la aplicación….
        /// </summary>
        public static string MsgRegisteringUser {
            get {
                return ResourceManager.GetString("MsgRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrando el grupo de usuario y sus miembros….
        /// </summary>
        public static string MsgRegisteringUserGroup {
            get {
                return ResourceManager.GetString("MsgRegisteringUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subiendo archivo APK.....
        /// </summary>
        public static string MsgUploadingApk {
            get {
                return ResourceManager.GetString("MsgUploadingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo de usuarios: {0}, fue registrado exitosamente.
        /// </summary>
        public static string MsgUserGroupRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("MsgUserGroupRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: {0}, fue registrado exitosamente.
        /// </summary>
        public static string MsgUserRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("MsgUserRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dada de baja.
        /// </summary>
        public static string PolicyStatusDisabled {
            get {
                return ResourceManager.GetString("PolicyStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string PolicyStatusEnabled {
            get {
                return ResourceManager.GetString("PolicyStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APLICACIONES.
        /// </summary>
        public static string TabApplications {
            get {
                return ResourceManager.GetString("TabApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPOSITIVOS MÓVILES.
        /// </summary>
        public static string TabDevices {
            get {
                return ResourceManager.GetString("TabDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERTAR.
        /// </summary>
        public static string TabInsert {
            get {
                return ResourceManager.GetString("TabInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIO.
        /// </summary>
        public static string TabStart {
            get {
                return ResourceManager.GetString("TabStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIOS.
        /// </summary>
        public static string TabUsers {
            get {
                return ResourceManager.GetString("TabUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISTA.
        /// </summary>
        public static string TabView {
            get {
                return ResourceManager.GetString("TabView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicaciones.
        /// </summary>
        public static string TitleApplications {
            get {
                return ResourceManager.GetString("TitleApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos Móviles.
        /// </summary>
        public static string TitleDevices {
            get {
                return ResourceManager.GetString("TitleDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exito!.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string TitleUsers {
            get {
                return ResourceManager.GetString("TitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicaciones.
        /// </summary>
        public static string ToolsApplication {
            get {
                return ResourceManager.GetString("ToolsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string ToolsUser {
            get {
                return ResourceManager.GetString("ToolsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar aplicación.
        /// </summary>
        public static string TooltipAddApp {
            get {
                return ResourceManager.GetString("TooltipAddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregue una aplicación simplemente seleccionando su apk.
        /// </summary>
        public static string TooltipAddAppDesc {
            get {
                return ResourceManager.GetString("TooltipAddAppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar reglas de directivas de usuario.
        /// </summary>
        public static string TooltipAddPolicyRule {
            get {
                return ResourceManager.GetString("TooltipAddPolicyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las reglas de directivas de usuarios permiten definir el acceso de los usuarios a diversos recursos, como aplicaciones, dispositivos, etc.
        /// </summary>
        public static string TooltipAddPolicyRuleDesc {
            get {
                return ResourceManager.GetString("TooltipAddPolicyRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar usuario.
        /// </summary>
        public static string TooltipAddUser {
            get {
                return ResourceManager.GetString("TooltipAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize esta opción para registrar un nuevo usuario, seleccionando un usuario válido de Active Directory®.
        /// </summary>
        public static string TooltipAddUserDesc {
            get {
                return ResourceManager.GetString("TooltipAddUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar grupo de usuarios.
        /// </summary>
        public static string TooltipAddUserGroup {
            get {
                return ResourceManager.GetString("TooltipAddUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregue grupos de usuarios, para poder asignarles aplicaciones.
        /// </summary>
        public static string TooltipAddUserGroupDesc {
            get {
                return ResourceManager.GetString("TooltipAddUserGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono de la aplicación.
        /// </summary>
        public static string TooltipApplicationIcon {
            get {
                return ResourceManager.GetString("TooltipApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir atrás.
        /// </summary>
        public static string TooltipBack {
            get {
                return ResourceManager.GetString("TooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver aplicaciones.
        /// </summary>
        public static string TooltipShowApps {
            get {
                return ResourceManager.GetString("TooltipShowApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra todas las aplicaciones registradas.
        /// </summary>
        public static string TooltipShowAppsDesc {
            get {
                return ResourceManager.GetString("TooltipShowAppsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver dispositivos.
        /// </summary>
        public static string TooltipShowDevices {
            get {
                return ResourceManager.GetString("TooltipShowDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra todos los dispositivos registrados, los authorizados y dados de baja.
        /// </summary>
        public static string TooltipShowDevicesDesc {
            get {
                return ResourceManager.GetString("TooltipShowDevicesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver usuarios.
        /// </summary>
        public static string TooltipShowUsers {
            get {
                return ResourceManager.GetString("TooltipShowUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra todos los usuarios registrados en la aplicación.
        /// </summary>
        public static string TooltipShowUsersDesc {
            get {
                return ResourceManager.GetString("TooltipShowUsersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registrado.
        /// </summary>
        public static string UserStatusNonRegistered {
            get {
                return ResourceManager.GetString("UserStatusNonRegistered", resourceCulture);
            }
        }
    }
}
